### PR TITLE
Change minimum version requirement of tap to 1.0.1

### LINKED ISSUE #5: Implicit dependency on version 1.0.1 of `tap` crate
The current dependency specification in Cargo.toml claim the crate works with any 1.x version of the `tap` crate, but [this export](https://github.com/myrrlyn/wyz/blob/main/src/comu.rs#L24) is only available starting from version 1.0.1.

To demonstrate, create an empty project with this `Cargo.toml` and run `cargo build`:
```toml
[dependencies]
wyz = "=0.4.0"
tap = "=1.0.0"
#tap = "=1.0.1" # Uncomment this to build successfully 
```

Probably a minor issue, I just encountered this when updating `bitvec` to 0.22. I had to run `cargo update` before the build would succeed, since without it Cargo tried to use the already resolved version 1.0.0 from its Cargo.lock file.

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #5.

### CODE REVIEW

**Comment by KiChjang** [comment]
@myrrlyn I encountered #5 while updating bitvec and I think this PR will solve it once and for all.

**Comment by dpc** [comment]
@myrrlyn Hi! This issue is causing min-version builds of projects using `bitvec` to fail. Can you please land and release.

BTW. Are you still maintaining this and other `bitvec` helper dependencies? Do you need help? Are you willing to share maintenance over them?

**Comment by myrrlyn** [comment]
I am still maintaining them I've just been otherwise pre-occupied for the last ... while. I'm sorry about the delays and I'm working on getting the project into a stable state where issues like these shouldn't crop up anymore.

**Comment by dpc** [comment]
@myrrlyn Thanks a lot and I understand completely!

**Pull request merged**
